<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Subject;

class EnhancedSubjectSeeder extends Seeder
{
    public function run(): void
    {
        $subjects = [
            // ===============================================
            // BS Electrical Engineering Technology - 1st Year, 1st Sem
            // ===============================================
            [
                'code' => 'GE1-ELECT',
                'name' => 'Purposive Communication',
                'units' => 3,
                'price_per_unit' => 364.00,
                'year_level' => '1st Year',
                'semester' => '1st Sem',
                'course' => 'BS Electrical Engineering Technology',
                'description' => 'General Education - Communication Skills',
                'has_lab' => false,
                'lab_fee' => 0,
                'is_active' => true,
            ],
            [
                'code' => 'GEELECT1-ELECT',
                'name' => 'Living in the IT Era',
                'units' => 3,
                'price_per_unit' => 364.00,
                'year_level' => '1st Year',
                'semester' => '1st Sem',
                'course' => 'BS Electrical Engineering Technology',
                'description' => 'GE Elective - IT Literacy',
                'has_lab' => true,
                'lab_fee' => 1656.00,
                'is_active' => true,
            ],
            [
                'code' => 'GE2-ELECT',
                'name' => 'Mathematics in the Modern World',
                'units' => 3,
                'price_per_unit' => 364.00,
                'year_level' => '1st Year',
                'semester' => '1st Sem',
                'course' => 'BS Electrical Engineering Technology',
                'description' => 'General Education - Mathematics',
                'has_lab' => false,
                'lab_fee' => 0,
                'is_active' => true,
            ],
            [
                'code' => 'MATH101-ELECT',
                'name' => 'Science, Technology & Society',
                'units' => 3,
                'price_per_unit' => 364.00,
                'year_level' => '1st Year',
                'semester' => '1st Sem',
                'course' => 'BS Electrical Engineering Technology',
                'description' => 'STS Course',
                'has_lab' => false,
                'lab_fee' => 0,
                'is_active' => true,
            ],
            [
                'code' => 'PHYS101-ELECT',
                'name' => 'Physics for Engineering Technologists',
                'units' => 3,
                'price_per_unit' => 364.00,
                'year_level' => '1st Year',
                'semester' => '1st Sem',
                'course' => 'BS Electrical Engineering Technology',
                'description' => 'Engineering Physics',
                'has_lab' => true,
                'lab_fee' => 1656.00,
                'is_active' => true,
            ],
            [
                'code' => 'COMP101-ELECT',
                'name' => 'Integrated Software Applications 1',
                'units' => 3,
                'price_per_unit' => 364.00,
                'year_level' => '1st Year',
                'semester' => '1st Sem',
                'course' => 'BS Electrical Engineering Technology',
                'description' => 'Computer Applications',
                'has_lab' => true,
                'lab_fee' => 1656.00,
                'is_active' => true,
            ],
            [
                'code' => 'PATHFIT1-ELECT',
                'name' => 'Movement Competency Training',
                'units' => 2,
                'price_per_unit' => 364.00,
                'year_level' => '1st Year',
                'semester' => '1st Sem',
                'course' => 'BS Electrical Engineering Technology',
                'description' => 'Physical Education',
                'has_lab' => false,
                'lab_fee' => 0,
                'is_active' => true,
            ],
            [
                'code' => 'NSTP1-ELECT',
                'name' => 'National Service Training Program 1',
                'units' => 3,
                'price_per_unit' => 364.00,
                'year_level' => '1st Year',
                'semester' => '1st Sem',
                'course' => 'BS Electrical Engineering Technology',
                'description' => 'NSTP Component',
                'has_lab' => false,
                'lab_fee' => 0,
                'is_active' => true,
            ],

            // ===============================================
            // BS Electronics Engineering Technology - 1st Year, 1st Sem
            // ===============================================
            [
                'code' => 'GE1-ECET',
                'name' => 'Purposive Communication',
                'units' => 3,
                'price_per_unit' => 364.00,
                'year_level' => '1st Year',
                'semester' => '1st Sem',
                'course' => 'BS Electronics Engineering Technology',
                'description' => 'General Education - Communication Skills',
                'has_lab' => false,
                'lab_fee' => 0,
                'is_active' => true,
            ],
            [
                'code' => 'GEELECT1-ECET',
                'name' => 'Living in the IT Era',
                'units' => 3,
                'price_per_unit' => 364.00,
                'year_level' => '1st Year',
                'semester' => '1st Sem',
                'course' => 'BS Electronics Engineering Technology',
                'description' => 'GE Elective - IT Literacy',
                'has_lab' => true,
                'lab_fee' => 1656.00,
                'is_active' => true,
            ],
            [
                'code' => 'GE2-ECET',
                'name' => 'Mathematics in the Modern World',
                'units' => 3,
                'price_per_unit' => 364.00,
                'year_level' => '1st Year',
                'semester' => '1st Sem',
                'course' => 'BS Electronics Engineering Technology',
                'description' => 'General Education - Mathematics',
                'has_lab' => false,
                'lab_fee' => 0,
                'is_active' => true,
            ],
            [
                'code' => 'GE3-ECET',
                'name' => 'Science, Technology & Society',
                'units' => 3,
                'price_per_unit' => 364.00,
                'year_level' => '1st Year',
                'semester' => '1st Sem',
                'course' => 'BS Electronics Engineering Technology',
                'description' => 'STS Course',
                'has_lab' => false,
                'lab_fee' => 0,
                'is_active' => true,
            ],
            [
                'code' => 'ELXT110',
                'name' => 'Basic Electricity and Electronics',
                'units' => 4,
                'price_per_unit' => 364.00,
                'year_level' => '1st Year',
                'semester' => '1st Sem',
                'course' => 'BS Electronics Engineering Technology',
                'description' => 'Fundamentals of Electricity and Electronics',
                'has_lab' => true,
                'lab_fee' => 1656.00,
                'is_active' => true,
            ],
            [
                'code' => 'MATH101-ECET',
                'name' => 'Calculus 1 - Differential Calculus',
                'units' => 3,
                'price_per_unit' => 364.00,
                'year_level' => '1st Year',
                'semester' => '1st Sem',
                'course' => 'BS Electronics Engineering Technology',
                'description' => 'Advanced Mathematics',
                'has_lab' => false,
                'lab_fee' => 0,
                'is_active' => true,
            ],
            [
                'code' => 'PHYS101-ECET',
                'name' => 'Physics for Engineering Technologies',
                'units' => 3,
                'price_per_unit' => 364.00,
                'year_level' => '1st Year',
                'semester' => '1st Sem',
                'course' => 'BS Electronics Engineering Technology',
                'description' => 'Engineering Physics',
                'has_lab' => false,
                'lab_fee' => 0,
                'is_active' => true,
            ],
            [
                'code' => 'COMP101-ECET',
                'name' => 'Integrated Software Applications',
                'units' => 3,
                'price_per_unit' => 364.00,
                'year_level' => '1st Year',
                'semester' => '1st Sem',
                'course' => 'BS Electronics Engineering Technology',
                'description' => 'Computer Applications',
                'has_lab' => true,
                'lab_fee' => 1656.00,
                'is_active' => true,
            ],
            [
                'code' => 'PATHFIT1-ECET',
                'name' => 'Movement Competency Training',
                'units' => 2,
                'price_per_unit' => 364.00,
                'year_level' => '1st Year',
                'semester' => '1st Sem',
                'course' => 'BS Electronics Engineering Technology',
                'description' => 'Physical Education',
                'has_lab' => false,
                'lab_fee' => 0,
                'is_active' => true,
            ],
            [
                'code' => 'NSTP1-ECET',
                'name' => 'National Service Training Program 1',
                'units' => 3,
                'price_per_unit' => 364.00,
                'year_level' => '1st Year',
                'semester' => '1st Sem',
                'course' => 'BS Electronics Engineering Technology',
                'description' => 'NSTP Component',
                'has_lab' => false,
                'lab_fee' => 0,
                'is_active' => true,
            ],
        ];

        foreach ($subjects as $subject) {
            Subject::updateOrCreate(
                ['code' => $subject['code']],
                $subject
            );
        }

        $this->command->info('✓ Enhanced subjects with OBE curriculum seeded successfully!');
    }
}